---

# Based on code from https://github.com/marketplace/actions/yaml-lint

name: Yaml Lint

on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

# This validation is equivalent to running on the command line:
#   yamllint -d relaxed --no-warnings
# and is controlled by the .yamllint.yml file
jobs:
  validate-YAML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - id: yaml-lint
        name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          no_warnings: true
          format: colored
          config_file: .yamllint.yml

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: yamllint-logfile
          path: ${{ steps.yaml-lint.outputs.logfile }}
